// Number Gussening Game

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>

int main()
{

    int number;
    int guess;
    int nguesses = 1;

    srand(time(0));
    number = rand() % 100 + 1; // Generates a random number between 1 to 100
    printf("\n");
    // printf("The Number is %d \n", number);
    // This is hidden dso the number generated by the computer can't be visible
    // printf("\n");
    // keep running the loop until the number is gussed.

    do
    {
        printf("Guess any number between 1 to 100- ");
        scanf("%d", &guess);

        if (guess > number)
        {
            printf("Lower Number Please !!! \n");
        }
        else if (guess < number)
        {
            printf("Higher Number Please !!! \n");
        }
        else
        {
            printf("You guessed it in %d attemptes !!! \n", nguesses);
        }
        nguesses++;
    } while (guess != number);
    printf("\n");

    return 0;
}